config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :ideas do
    :comments
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :suggestion
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :suggestions
  has_many :comments
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :idea
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas
  has_many :suggestions, through: :ideas
  has_many :comments, through: :ideas
  has_many :comments, through: :suggestions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_idea, only: [:index, :new, :show, :create, :edit, :update, :destroy]

  def index
    comments = @idea.comments
    render :index, locals: { idea: @idea, comments: comments }
  end

  def show
    @comments = current_user.comments.find(params[:id])
    render :show, locals: { idea: @idea, comment: @comment }
  end

  def new
    @comment = current_user.comments.new
    render :new, locals: { idea: @idea, comment: @comment }
  end
  
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to idea_comment_path(@idea, @comment), notice: 'comment was successfully created.'
    else
      render :new, locals: { comment: @comment, idea: @idea }
    end
  end

  def edit
     @comment = Comment.find(params[:id])
    render :edit, locals: { idea: @idea, comment: @comment }
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to idea_comment_path(idea_id = params[:idea_id], @comment), notice: 'comment was successfully updated.'
    else
      render :edit, locals: { idea: @idea, comment: @comments }
    end
  end

  def destroy
     @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to idea_comments_path(idea_id = params[:idea_id]), notice: 'comment was successfully destroyed.'
  end

  private

  def find_idea
    @idea = Idea.find(params[:idea_id])
  rescue ActiveRecord::RecordNotFound
    render "errors/not_found", status: 404
  end

  def comment_params
    new_params = params.permit(:body)
    new_params['idea_id'] = params[:idea_id]
  end
end  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ideas_controller.rb
class IdeasController < HomeController
  before_action :find_idea, only: [:show, :edit, :update, :destroy]

  def new
    @idea = Idea.new
  end

  def index
    @ideas = Idea.all
  end

  def show
    render :show, locals: { idea: @idea }
  end

  def create
    @idea = current_user.ideas.new(idea_params)
    if @idea.save
      redirect_to idea_path(@idea), notice: 'idea was successfully created.'
    else
      render :new, locals: { idea: @idea }
    end
  end

  def edit
    render :edit, locals: { idea: @idea }
  end

  def update
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'idea was successfully updated.'
    else
      render :edit, locals: { idea: @idea }
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path, notice: 'idea was successfully destroyed.'
  end

private

  def find_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:id, :title, :summary, :votes, :collaborators)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<tbody>
   <% comments.each do |comment| %>
     <%= render comment, comment: comment %>
   <% end %>
 </tbody>

app/views/comments/_form.html.erb
<%= form_for [idea, comment] do |f| %>
   <% if comment.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
 
       <ul>
       <% comment.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>
 
   <div>
     <label for="body">Comment:</label>: 
     <input type="text" name="body" id="body value="<%= comment.body%>" required />
   </div>
 
   <div class="actions">
     <%= f.submit "Submit" %>
   </div>
 <% end %>

app/views/comments/edit.html.erb
edit<h1>Editing Comments</h1>
 
 <%= render 'form', comment: comment, idea: idea %>
 
 <%= link_to 'Show', idea_comment_path %> |
 <%= link_to 'Back', idea_comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
 
 <h1>Comment for <%= @idea.name %> </h1>
 
 <table>
   <thead>
     <tr>
       <th>Body</th>
       <th colspan="3"></th>
     </tr>
   </thead>
 
   <tbody>
     <% comments.each do |Comment| %>
       <tr>
         <td><%= comment.body %></td>
 
         <td><%= link_to 'Show', comment.idea %></td>
         <td><%= link_to 'Edit', edit_idea_comment_path(@idea_id = params[:idea_id], Comment) %></td>
         <td><%= link_to 'Destroy', idea_comment_path(@comment_id = params[:comment_id], product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>
 </table>
 
 <br>
 
 <%= link_to 'New Comment', new_idea_comment_path %>

app/views/comments/new.html.erb
<h1>Comment for <%= idea.name.capitalize %></h1>
 <%= render 'form', comment: comment, idea: idea %>
 <%= link_to 'Back', idea_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
 <h1><%= @idea.name.capitalize %> is:</h1>
 <div><%= @comments.body %>!</div>
 <%= link_to 'Edit', edit_idea_comment_path(@idea_id = params[:idea_id], @comments) %> |
 <%= link_to 'Back', idea_comment_path %>

app/views/home/index.html.erb
<body id="background">
  <div class="jumbotron" id="intro-container">
    <h1 class="text-center" id="title">Idea<em>Ocracy</em></h1>
    <hr />
    <h2 class="text-center" id="tagline">Clarify, collaborate and codify ideas into future projects</h2>
    <div class="text-center">
      <%= button_to 'View Ideas', ideas_path, method: :get, class: "btn btn-success intro-buttons" %>
      <%= button_to 'Create Idea', new_idea_path, method: :get, class: "btn btn-info intro-buttons" %>
    </div>
  </div>
</body>

app/views/ideas/_form.html.erb
<%= form_for (idea) do |f| %>

  <div class="text-center">
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, required: 'required' %>
    </div>

    <div class="field">
      <%= f.label :summary %><br />
      <%= f.text_area :summary, required: 'required' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>
 
 <%= render 'form', idea: idea %>
 <%= link_to 'Show', idea %> |
 <%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
  <h1 class="text-center">Ideas</h1>
  <% if @ideas.any? %>
    <% @ideas.each do |idea| %>
      <p><%= link_to idea.title, idea_path(idea.id) %> <%= idea.created_at.strftime('%y-%m-%d %H:%m') %></p>
      <p><%= idea.summary %></p> 
      <td><%= link_to 'Details', idea_path(idea) %></td><br><br>
      <!-- <td><%#= link_to 'Write a comment', new_idea_comment_path(idea) %></td> -->   
    <% end %>
  <% else %>
    Nothing yet
  <% end %>
  <%= link_to 'Create New Idea', new_idea_path, class: 'btn btn-info' %>

app/views/ideas/new.html.erb
<h1 class="text-center">Post an Idea</h1>

<%= render 'form', { idea: @idea } %>
<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= idea.title %></h1>
<div><%= idea.summary %></div><br>
<%= link_to 'Edit', edit_idea_path(idea) %> |
<td><%= link_to 'Delete', idea_path(idea), method: :delete, data: { confirm: 'Are you sure?' } %></td><br>
<%= link_to 'Back', ideas_path, class: 'btn btn-info' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideaocracy</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="home-page">
    <nav class="navbar navbar-inverse bg-inverse">
      <a class="navbar-brand" href="#">Ideaocracy</a>
    </nav>
    <%= yield %>
  </body>
</html>